function pushIf(rows: Array<[string, string]>, label: string, value: unknown) {
  if (value === null || value === undefined || value === "") return;
  rows.push([label, String(value)]);
}

export default function EventSummary({ event }: { event: Record<string, unknown> }) {
  const raw = (event.raw as Record<string, unknown>) ?? {};
  const category = String((event.event as Record<string, unknown> | undefined)?.category ?? "unknown");
  const eventMeta = (event.event as Record<string, unknown>) ?? {};
  const process = (event.process as Record<string, unknown>) ?? {};
  const file = (event.file as Record<string, unknown>) ?? {};
  const network = (event.network as Record<string, unknown>) ?? {};
  const windows = (event.windows as Record<string, unknown>) ?? {};
  const user = (event.user as Record<string, unknown>) ?? {};
  const host = (event.host as Record<string, unknown>) ?? {};
  const execution = (event.execution as Record<string, unknown>) ?? {};
  const browser = (event.browser as Record<string, unknown>) ?? {};
  const email = (event.email as Record<string, unknown>) ?? {};
  const velociraptor = (event.velociraptor as Record<string, unknown>) ?? {};
  const url = (event.url as Record<string, unknown>) ?? {};
  const download = (event.download as Record<string, unknown>) ?? {};
  const registry = (event.registry as Record<string, unknown>) ?? {};
  const lnk = (event.lnk as Record<string, unknown>) ?? {};
  const jumplist = (event.jumplist as Record<string, unknown>) ?? {};
  const usb = (event.usb as Record<string, unknown>) ?? {};
  const bits = (event.bits as Record<string, unknown>) ?? {};
  const wmi = (event.wmi as Record<string, unknown>) ?? {};
  const autoruns = (event.autoruns as Record<string, unknown>) ?? {};
  const cloud = (event.cloud as Record<string, unknown>) ?? {};
  const wlan = (event.wlan as Record<string, unknown>) ?? {};
  const dns = (event.dns as Record<string, unknown>) ?? {};
  const persistence = (event.persistence as Record<string, unknown>) ?? {};
  const volume = (event.volume as Record<string, unknown>) ?? {};
  const shellbag = (event.shellbag as Record<string, unknown>) ?? {};
  const mft = (event.mft as Record<string, unknown>) ?? {};
  const filesystem = (event.filesystem as Record<string, unknown>) ?? {};
  const usn = (event.usn as Record<string, unknown>) ?? {};
  const recycleBin = ((event.recycle as Record<string, unknown>) ?? (event.recycle_bin as Record<string, unknown>) ?? {});
  const srum = (event.srum as Record<string, unknown>) ?? {};
  const amcache = (event.amcache as Record<string, unknown>) ?? {};
  const shimcache = (event.shimcache as Record<string, unknown>) ?? {};
  const appcompat = (event.appcompat as Record<string, unknown>) ?? {};
  const task = (event.task as Record<string, unknown>) ?? {};
  const detection = (event.detection as Record<string, unknown>) ?? {};
  const powershell = (event.powershell as Record<string, unknown>) ?? {};
  const service = (event.service as Record<string, unknown>) ?? {};
  const artifactType = String((event.artifact as Record<string, unknown> | undefined)?.type ?? "");
  const isExecutionArtifact = artifactType === "amcache" || artifactType === "shimcache" || artifactType === "appcompat";

  const rows: Array<[string, string]> = [];
  const timestampStatus = String(event.timestamp_status ?? raw.timestamp_status ?? "");
  const timestampWarning = String(event.timestamp_warning ?? raw.timestamp_warning ?? "");
  const timestampOriginal = event.timestamp_original ?? event.raw_timestamp ?? event.original_timestamp ?? raw.timestamp_original ?? raw.raw_timestamp ?? raw.original_timestamp;

  if (timestampStatus === "suspicious" || timestampStatus === "invalid" || timestampWarning) {
    pushIf(rows, "Timestamp warning", "Suspicious timestamp preserved but not used for timeline.");
    pushIf(rows, "Timestamp status", timestampStatus || "suspicious");
    pushIf(rows, "Original timestamp", timestampOriginal);
  }

  const pushExecutionArtifactRows = () => {
    pushIf(rows, "Source", execution.source);
    pushIf(rows, "Interpretation", execution.interpretation);
    pushIf(rows, "Confidence", execution.confidence);
    pushIf(rows, "Execution confirmed", execution.is_execution_confirmed);
    pushIf(rows, "Program / file", process.name ?? file.name ?? amcache.program_name ?? appcompat.name);
    pushIf(rows, "Path", file.path ?? process.path ?? amcache.file_path ?? shimcache.path ?? appcompat.path);
    pushIf(rows, "Publisher", process.publisher ?? amcache.publisher);
    pushIf(rows, "Product", process.product_name ?? amcache.product_name);
    pushIf(rows, "Version", process.product_version ?? amcache.product_version ?? amcache.program_version);
    pushIf(rows, "SHA1", file.hash_sha1 ?? file.sha1);
    pushIf(rows, "SHA256", file.hash_sha256 ?? file.sha256);
    pushIf(rows, "MD5", file.md5);
    pushIf(rows, "Install date", execution.install_date ?? amcache.install_date);
    pushIf(rows, "Uninstall date", amcache.uninstall_date);
    pushIf(rows, "Link date", execution.link_date ?? amcache.link_date);
    pushIf(rows, "Compile time", execution.compile_time ?? amcache.compile_time);
    pushIf(rows, "Key last write", execution.last_seen ?? amcache.key_last_write_time);
    pushIf(rows, "Last modified", execution.last_modified ?? shimcache.last_modified_time ?? appcompat.last_modified);
    pushIf(rows, "Path hash", amcache.path_hash);
    pushIf(rows, "Binary type", amcache.binary_type);
    pushIf(rows, "Language", amcache.language);
    pushIf(rows, "Is OS component", amcache.is_os_component);
    pushIf(rows, "Program ID", amcache.program_id);
    pushIf(rows, "File ID", amcache.file_id);
    pushIf(rows, "Key path", amcache.key_path);
    pushIf(rows, "Entry number", shimcache.entry_number ?? appcompat.entry_number);
    pushIf(rows, "Position", shimcache.position);
    pushIf(rows, "Executed flag", shimcache.executed);
    pushIf(rows, "Control set", shimcache.control_set);
    pushIf(rows, "Timestamp precision", event.timestamp_precision);
    pushIf(rows, "Source file", amcache.source_file ?? shimcache.source_file ?? appcompat.source_file ?? event.source_file);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  };

  if (isExecutionArtifact && ["execution", "file", "program_inventory"].includes(category)) {
    pushExecutionArtifactRows();
  } else if (artifactType === "powershell" || category === "powershell") {
    pushIf(rows, "Artifact type", powershell.artifact_type);
    pushIf(rows, "User", user.name ?? powershell.username);
    pushIf(rows, "RunAs", powershell.run_as);
    pushIf(rows, "Source file", powershell.source_file ?? event.source_file);
    pushIf(rows, "Line number", powershell.line_number);
    pushIf(rows, "Command", powershell.command ?? process.command_line);
    pushIf(rows, "Decoded preview", powershell.decoded_command_preview);
    pushIf(rows, "URLs", Array.isArray(powershell.urls) ? powershell.urls.join(" | ") : powershell.urls);
    pushIf(rows, "Domains", Array.isArray(powershell.domains) ? powershell.domains.join(" | ") : powershell.domains);
    pushIf(rows, "Paths", Array.isArray(powershell.paths) ? powershell.paths.join(" | ") : powershell.paths);
    pushIf(rows, "Indicators", Array.isArray(powershell.indicators) ? powershell.indicators.join(" | ") : powershell.indicators);
    pushIf(rows, "Transcript start", powershell.transcript_start_time);
    pushIf(rows, "Transcript end", powershell.transcript_end_time);
    pushIf(rows, "Machine", powershell.machine);
    pushIf(rows, "Host application", powershell.host_application);
    pushIf(rows, "Process ID", powershell.process_id);
    pushIf(rows, "PS version", powershell.ps_version);
    pushIf(rows, "Has encoded", powershell.has_encoded_command);
    pushIf(rows, "Has download", powershell.has_download);
    pushIf(rows, "Has IEX", powershell.has_iex);
    pushIf(rows, "ExecutionPolicy bypass", powershell.has_execution_policy_bypass);
    pushIf(rows, "Defender tampering", powershell.has_defender_tampering);
    pushIf(rows, "Persistence indicators", powershell.has_persistence);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "email" || category === "email") {
    const emailFrom = (email.from as Record<string, unknown> | undefined) ?? {};
    const emailHeaders = (email.headers as Record<string, unknown> | undefined) ?? {};
    pushIf(rows, "Subject", email.subject);
    pushIf(rows, "Message-ID", email.message_id);
    pushIf(rows, "From", emailFrom.address ?? emailFrom.display_name);
    pushIf(rows, "To", Array.isArray(email.to) ? email.to.join(" | ") : email.to);
    pushIf(rows, "Cc", Array.isArray(email.cc) ? email.cc.join(" | ") : email.cc);
    pushIf(rows, "Reply-To", emailHeaders.reply_to);
    pushIf(rows, "Return-Path", emailHeaders.return_path);
    pushIf(rows, "SPF", emailHeaders.spf_result);
    pushIf(rows, "DKIM", emailHeaders.dkim_result);
    pushIf(rows, "DMARC", emailHeaders.dmarc_result);
    pushIf(rows, "Authentication-Results", emailHeaders.authentication_results);
    pushIf(rows, "X-Mailer", emailHeaders.x_mailer);
    pushIf(rows, "User-Agent", emailHeaders.user_agent);
    pushIf(rows, "X-Originating-IP", emailHeaders.x_originating_ip);
    pushIf(rows, "Mailbox", email.mailbox_name ?? email.mailbox_type);
    pushIf(rows, "Body preview", email.body_preview);
    pushIf(rows, "Attachments", Array.isArray(email.attachments) ? email.attachments.map((item) => String((item as Record<string, unknown>).file_name ?? "")).filter(Boolean).join(" | ") : email.attachments);
    pushIf(rows, "Suspicious attachment count", email.suspicious_attachment_count);
    pushIf(rows, "Unsupported reason", email.unsupported_reason);
    pushIf(rows, "Parser status", email.parser_status);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "user_activity" || category === "user_activity") {
    const folder = (event.folder as Record<string, unknown>) ?? {};
    const mru = (event.mru as Record<string, unknown>) ?? {};
    const office = (event.office as Record<string, unknown>) ?? {};
    const userActivity = (event.user_activity as Record<string, unknown>) ?? {};
    pushIf(rows, "Activity", userActivity.kind ?? eventMeta.action ?? eventMeta.type);
    pushIf(rows, "User", user.name);
    pushIf(rows, "SID", user.id ?? user.sid);
    pushIf(rows, "Application", userActivity.application ?? process.name);
    pushIf(rows, "Command", process.command_line);
    pushIf(rows, "Process path", process.path);
    pushIf(rows, "Document path", file.path);
    pushIf(rows, "Folder path", folder.path);
    pushIf(rows, "Registry hive", registry.hive);
    pushIf(rows, "Registry key", registry.key_path);
    pushIf(rows, "Registry value", registry.value_name);
    pushIf(rows, "Registry data", registry.value_data);
    pushIf(rows, "MRU order", mru.order);
    pushIf(rows, "MRU list", mru.list);
    pushIf(rows, "Office app", office.app);
    pushIf(rows, "Office version", office.version);
    pushIf(rows, "Trusted document", office.trusted_document);
    pushIf(rows, "Macro trust possible", office.macro_trust_possible);
    pushIf(rows, "Execution confirmed", execution.is_execution_confirmed);
    pushIf(rows, "Execution confidence", execution.confidence);
    pushIf(rows, "Run count", execution.run_count);
    pushIf(rows, "Last run", execution.last_run);
    pushIf(rows, "Timestamp precision", event.timestamp_precision);
    pushIf(rows, "Source file", event.source_file);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "ntfs" || (artifactType === "mft" && event.ntfs)) {
    const ntfs = (event.ntfs as Record<string, unknown>) ?? {};
    const folder = (event.folder as Record<string, unknown>) ?? {};
    pushIf(rows, "File path", file.path);
    pushIf(rows, "Folder path", folder.path);
    pushIf(rows, "Extension", file.extension);
    pushIf(rows, "NTFS source", ntfs.source);
    pushIf(rows, "Reason", ntfs.reason);
    pushIf(rows, "USN", ntfs.usn);
    pushIf(rows, "Zone ID", ntfs.zone_id);
    pushIf(rows, "Zone", ntfs.zone_name);
    pushIf(rows, "Host URL", ntfs.host_url);
    pushIf(rows, "Referrer URL", ntfs.referrer_url);
    pushIf(rows, "Old name", ntfs.old_name);
    pushIf(rows, "New name", ntfs.new_name);
    pushIf(rows, "Shadow ID", ntfs.shadow_id);
    pushIf(rows, "Snapshot time", ntfs.snapshot_time);
    pushIf(rows, "Timestamp source", ntfs.timestamp_source);
    pushIf(rows, "Source file", event.source_file);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "windows_ui" || category === "windows_ui") {
    const folder = (event.folder as Record<string, unknown>) ?? {};
    const app = (event.app as Record<string, unknown>) ?? {};
    const notification = (event.notification as Record<string, unknown>) ?? {};
    const activity = (event.activity as Record<string, unknown>) ?? {};
    const office = (event.office as Record<string, unknown>) ?? {};
    const thumbnail = (event.thumbnail as Record<string, unknown>) ?? {};
    const windowsSearch = (event.windows_search as Record<string, unknown>) ?? {};
    const windowsUi = (event.windows_ui as Record<string, unknown>) ?? {};
    pushIf(rows, "UI source", windowsUi.source);
    pushIf(rows, "App name", app.name);
    pushIf(rows, "App ID", app.id);
    pushIf(rows, "App package", app.package);
    pushIf(rows, "File path", file.path);
    pushIf(rows, "Folder path", folder.path);
    pushIf(rows, "Notification title", notification.title);
    pushIf(rows, "Notification body", notification.body_preview);
    pushIf(rows, "Notification created", notification.created_time);
    pushIf(rows, "Notification expires", notification.expires_time);
    pushIf(rows, "Activity display", activity.display_text);
    pushIf(rows, "Activity URI", activity.activation_uri);
    pushIf(rows, "Activity start", activity.start_time);
    pushIf(rows, "Activity end", activity.end_time);
    pushIf(rows, "Thumbnail source path", thumbnail.source_path);
    pushIf(rows, "Thumbnail cache ID", thumbnail.cache_id);
    pushIf(rows, "Thumbnail size", thumbnail.width && thumbnail.height ? `${thumbnail.width}x${thumbnail.height}` : undefined);
    pushIf(rows, "Indexed path", windowsSearch.indexed_path);
    pushIf(rows, "Content type", windowsSearch.content_type);
    pushIf(rows, "Indexed last modified", windowsSearch.last_modified);
    pushIf(rows, "Office app", office.app);
    pushIf(rows, "Office alert", office.alert_text);
    pushIf(rows, "Office document", office.document_path);
    pushIf(rows, "Office cache ID", office.cache_id);
    pushIf(rows, "Timestamp source", windowsUi.timestamp_source);
    pushIf(rows, "Source file", event.source_file);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "defender" || category === "detection") {
    pushIf(rows, "Threat name", detection.threat_name);
    pushIf(rows, "Threat ID", detection.threat_id);
    pushIf(rows, "Severity", detection.severity ?? eventMeta.severity);
    pushIf(rows, "Category", detection.category);
    pushIf(rows, "Action", detection.action ?? eventMeta.action);
    pushIf(rows, "Status", detection.status);
    pushIf(rows, "Remediation action", detection.remediation_action);
    pushIf(rows, "Detection source", detection.detection_source);
    pushIf(rows, "Resource", detection.resource);
    pushIf(rows, "File path", file.path ?? detection.path);
    pushIf(rows, "Container file", detection.container_file);
    pushIf(rows, "Process name", process.name);
    pushIf(rows, "Process path", process.path);
    pushIf(rows, "User", user.name ?? detection.user);
    pushIf(rows, "User SID", user.sid ?? detection.user_sid);
    pushIf(rows, "Product", detection.product_name);
    pushIf(rows, "Engine version", detection.engine_version);
    pushIf(rows, "Signature version", detection.signature_version);
    pushIf(rows, "SHA1", file.hash_sha1 ?? file.sha1);
    pushIf(rows, "SHA256", file.hash_sha256 ?? file.sha256);
    pushIf(rows, "MD5", file.md5);
    pushIf(rows, "Detection timestamp", detection.timestamp);
    pushIf(rows, "Source file", detection.source_file ?? event.source_file);
    pushIf(rows, "Line number", detection.line_number);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "usb" || category === "device") {
    pushIf(rows, "Device instance ID", usb.device_instance_id);
    pushIf(rows, "Raw instance ID", usb.raw_instance_id);
    pushIf(rows, "Vendor", usb.vendor);
    pushIf(rows, "Product", usb.product);
    pushIf(rows, "Revision", usb.revision);
    pushIf(rows, "VID", usb.vid);
    pushIf(rows, "PID", usb.pid);
    pushIf(rows, "Serial", usb.serial);
    pushIf(rows, "Friendly name", usb.friendly_name);
    pushIf(rows, "Container ID", usb.container_id);
    pushIf(rows, "Parent ID prefix", usb.parent_id_prefix);
    pushIf(rows, "Class GUID", usb.class_guid);
    pushIf(rows, "Class name", usb.class_name);
    pushIf(rows, "Service", usb.service);
    pushIf(rows, "Driver", usb.driver);
    pushIf(rows, "Driver provider", usb.driver_provider);
    pushIf(rows, "Driver date", usb.driver_date);
    pushIf(rows, "Driver version", usb.driver_version);
    pushIf(rows, "INF path", usb.inf_path);
    pushIf(rows, "Install status", usb.install_status);
    pushIf(rows, "Result code", usb.result_code);
    pushIf(rows, "First install", usb.first_install_time);
    pushIf(rows, "Install time", usb.install_time);
    pushIf(rows, "Last arrival", usb.last_arrival_time);
    pushIf(rows, "Last removal", usb.last_removal_time);
    pushIf(rows, "Section start", usb.section_start_time);
    pushIf(rows, "Section end", usb.section_end_time);
    pushIf(rows, "Device type", usb.device_type);
    pushIf(rows, "Timestamp precision", event.timestamp_precision);
    pushIf(rows, "Drive letter", volume.drive_letter);
    pushIf(rows, "Volume GUID", volume.guid);
    pushIf(rows, "Volume serial", volume.serial);
    pushIf(rows, "Volume label", volume.label);
    pushIf(rows, "Drive type", volume.drive_type);
    pushIf(rows, "Mounted device", volume.mounted_device);
    pushIf(rows, "DOS device", volume.dos_device);
    pushIf(rows, "Source file", usb.source_file ?? event.source_file);
    pushIf(rows, "Line start", usb.line_start);
    pushIf(rows, "Line end", usb.line_end);
    pushIf(rows, "Parse warnings", Array.isArray(usb.parse_warnings) ? usb.parse_warnings.join(" | ") : usb.parse_warnings);
    pushIf(rows, "Velociraptor original path", velociraptor.original_path);
    pushIf(rows, "Velociraptor normalized path", velociraptor.normalized_windows_path);
    pushIf(rows, "Velociraptor category", velociraptor.artifact_category);
    pushIf(rows, "Velociraptor parser status", velociraptor.parser_status);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "bits" || (category === "network" && (bits.job_id || bits.remote_url || bits.notify_cmd_line))) {
    pushIf(rows, "Job ID", bits.job_id);
    pushIf(rows, "Job GUID", bits.job_guid);
    pushIf(rows, "Display name", bits.display_name);
    pushIf(rows, "Description", bits.description);
    pushIf(rows, "Owner", bits.owner ?? user.name);
    pushIf(rows, "Owner SID", bits.owner_sid ?? user.sid);
    pushIf(rows, "State", bits.state);
    pushIf(rows, "Type", bits.type);
    pushIf(rows, "Priority", bits.priority);
    pushIf(rows, "Remote URL", bits.remote_url ?? url.full);
    pushIf(rows, "Remote name", bits.remote_name);
    pushIf(rows, "Local path", bits.local_path ?? file.path);
    pushIf(rows, "Local name", bits.local_name ?? file.name);
    pushIf(rows, "Files total", bits.files_total);
    pushIf(rows, "Files transferred", bits.files_transferred);
    pushIf(rows, "Bytes total", bits.bytes_total ?? download.total_bytes);
    pushIf(rows, "Bytes transferred", bits.bytes_transferred ?? download.received_bytes);
    pushIf(rows, "Creation time", bits.creation_time);
    pushIf(rows, "Modification time", bits.modification_time);
    pushIf(rows, "Transfer completion", bits.transfer_completion_time);
    pushIf(rows, "Expiration time", bits.expiration_time);
    pushIf(rows, "Notify command", bits.notify_cmd_line);
    pushIf(rows, "Notify flags", bits.notify_flags);
    pushIf(rows, "Retry delay", bits.retry_delay);
    pushIf(rows, "No progress timeout", bits.no_progress_timeout);
    pushIf(rows, "Minimum retry delay", bits.minimum_retry_delay);
    pushIf(rows, "Error code", bits.error_code);
    pushIf(rows, "Error description", bits.error_description);
    pushIf(rows, "Parser status", bits.parser_status);
    pushIf(rows, "Source file", bits.source_file ?? event.source_file);
    pushIf(rows, "Raw qmgr path", bits.raw_qmgr_path);
    pushIf(rows, "Timestamp precision", event.timestamp_precision);
    pushIf(rows, "URL domain", url.domain);
    pushIf(rows, "URL scheme", url.scheme);
    pushIf(rows, "Network application", network.application);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "wmi" || category === "wmi") {
    pushIf(rows, "Namespace", wmi.namespace);
    pushIf(rows, "Class", wmi.class_name);
    pushIf(rows, "Instance name", wmi.instance_name);
    pushIf(rows, "Name", wmi.name);
    pushIf(rows, "Filter name", wmi.filter_name);
    pushIf(rows, "Consumer name", wmi.consumer_name);
    pushIf(rows, "Consumer type", wmi.consumer_type);
    pushIf(rows, "Query", wmi.query);
    pushIf(rows, "Query language", wmi.query_language);
    pushIf(rows, "Event namespace", wmi.event_namespace);
    pushIf(rows, "Command line template", wmi.command_line_template);
    pushIf(rows, "Executable path", wmi.executable_path ?? process.path);
    pushIf(rows, "Working directory", wmi.working_directory);
    pushIf(rows, "Script preview", wmi.script_preview);
    pushIf(rows, "Script text", wmi.script_text);
    pushIf(rows, "Scripting engine", wmi.scripting_engine);
    pushIf(rows, "Binding filter", wmi.binding_filter);
    pushIf(rows, "Binding consumer", wmi.binding_consumer);
    pushIf(rows, "Creator SID", wmi.creator_sid ?? user.sid);
    pushIf(rows, "Creator user", wmi.creator_user ?? user.name);
    pushIf(rows, "Last write", wmi.last_write_time);
    pushIf(rows, "Created time", wmi.created_time);
    pushIf(rows, "Modified time", wmi.modified_time);
    pushIf(rows, "Timestamp precision", event.timestamp_precision);
    pushIf(rows, "Timestamp interpretation", wmi.timestamp_interpretation);
    pushIf(rows, "URL", url.full);
    pushIf(rows, "Domain", url.domain ?? network.domain);
    pushIf(rows, "Source file", wmi.source_file ?? event.source_file);
    pushIf(rows, "Repository path", wmi.repository_path);
    pushIf(rows, "Parser status", wmi.parser_status);
    pushIf(rows, "Velociraptor original path", velociraptor.original_path);
    pushIf(rows, "Velociraptor normalized path", velociraptor.normalized_windows_path);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "autoruns" || artifactType === "autorun" || autoruns.entry_location || persistence.mechanism) {
    pushIf(rows, "Category", autoruns.category);
    pushIf(rows, "Mechanism", persistence.mechanism ?? autoruns.artifact_type);
    pushIf(rows, "Entry location", autoruns.entry_location ?? persistence.location);
    pushIf(rows, "Entry", autoruns.entry ?? persistence.name);
    pushIf(rows, "Enabled", autoruns.enabled ?? persistence.enabled);
    pushIf(rows, "Profile", autoruns.profile);
    pushIf(rows, "User", autoruns.user ?? persistence.user ?? user.name);
    pushIf(rows, "SID", autoruns.sid ?? persistence.sid ?? user.sid);
    pushIf(rows, "Image path", autoruns.image_path ?? persistence.path ?? file.path);
    pushIf(rows, "Launch string", autoruns.launch_string);
    pushIf(rows, "Command line", autoruns.command_line ?? persistence.command ?? process.command_line);
    pushIf(rows, "Arguments", autoruns.arguments);
    pushIf(rows, "Working directory", autoruns.working_directory);
    pushIf(rows, "Description", autoruns.description);
    pushIf(rows, "Publisher", autoruns.publisher);
    pushIf(rows, "Company", autoruns.company);
    pushIf(rows, "Signer", autoruns.signer);
    pushIf(rows, "Signed", autoruns.signed);
    pushIf(rows, "Verified", autoruns.verified);
    pushIf(rows, "MD5", autoruns.hash_md5 ?? file.md5);
    pushIf(rows, "SHA1", autoruns.hash_sha1 ?? file.hash_sha1);
    pushIf(rows, "SHA256", autoruns.hash_sha256 ?? file.hash_sha256);
    pushIf(rows, "PE SHA1", autoruns.pe_sha1);
    pushIf(rows, "PE SHA256", autoruns.pe_sha256);
    pushIf(rows, "VirusTotal", autoruns.virus_total);
    pushIf(rows, "VT detection", autoruns.vt_detection);
    pushIf(rows, "VT link", autoruns.vt_link);
    pushIf(rows, "Task", task.name);
    pushIf(rows, "Service", eventMeta.type?.toString().includes("service") ? (event.service as Record<string, unknown> | undefined)?.name : undefined);
    pushIf(rows, "WMI consumer", wmi.consumer_name);
    pushIf(rows, "Registry key", registry.key_path);
    pushIf(rows, "Timestamp precision", event.timestamp_precision);
    pushIf(rows, "Timestamp interpretation", autoruns.timestamp_interpretation);
    pushIf(rows, "Source file", autoruns.source_file ?? event.source_file);
    pushIf(rows, "Parser status", autoruns.parser_status);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "cloud_sync" || cloud.provider || cloud.sync_root) {
    const cloudArtifactType = String(cloud.artifact_type ?? "");
    const artifactKind =
      cloudArtifactType === "cloud_client_config" ? "Client config"
      : cloudArtifactType === "cloud_client_log" ? "Client log"
      : cloudArtifactType === "cloud_file_activity" ? "Cloud file activity"
      : cloudArtifactType === "cloud_sync_root" || cloudArtifactType.endsWith("_folder") ? "Sync root"
      : cloudArtifactType === "cloud_staging_candidate" ? "Staging candidate"
      : cloudArtifactType === "possible_cloud_exfiltration" ? "Possible exfiltration"
      : cloudArtifactType ? cloudArtifactType
      : undefined;
    const cloudEventType = String(eventMeta.type ?? "");
    const sourceValue = String(cloud.source_file ?? event.source_file ?? "-");
    pushIf(rows, "Provider", cloud.provider ?? network.application);
    pushIf(rows, "Artifact kind", artifactKind);
    pushIf(rows, "Account", cloud.account);
    pushIf(rows, "Account email", cloud.account_email);
    pushIf(rows, "User", cloud.user ?? user.name);
    pushIf(rows, "Sync root", cloud.sync_root);
    if (cloudEventType === "cloud_client_config" || cloudEventType === "cloud_client_log") {
      pushIf(rows, "Source", sourceValue);
    } else {
      pushIf(rows, "Local path", cloud.local_path ?? file.path);
    }
    pushIf(rows, "Remote path", cloud.remote_path);
    pushIf(rows, "Cloud path", cloud.cloud_path);
    pushIf(rows, "Status", cloud.status);
    pushIf(rows, "Sync status", cloud.sync_status);
    pushIf(rows, "Hydration", cloud.hydration_status);
    pushIf(rows, "Direction", cloud.direction);
    pushIf(rows, "Created", cloud.created_time ?? file.created);
    pushIf(rows, "Modified", cloud.modified_time ?? file.modified);
    pushIf(rows, "Accessed", cloud.accessed_time ?? file.accessed);
    pushIf(rows, "Deleted", cloud.deleted_time ?? file.deleted);
    pushIf(rows, "Last sync", cloud.last_sync_time);
    pushIf(rows, "Last upload", cloud.last_upload_time);
    pushIf(rows, "Last download", cloud.last_download_time);
    pushIf(rows, "Detection method", cloud.detection_method);
    pushIf(rows, "Timestamp precision", event.timestamp_precision);
    pushIf(rows, "Timestamp interpretation", cloud.timestamp_interpretation);
    pushIf(rows, "URL", url.full ?? download.url);
    pushIf(rows, "Domain", url.domain ?? network.domain);
    pushIf(rows, "Source file", sourceValue);
    pushIf(rows, "Parser status", cloud.parser_status);
    pushIf(rows, "Velociraptor original path", velociraptor.original_path);
    pushIf(rows, "Velociraptor normalized path", velociraptor.normalized_windows_path);
    pushIf(rows, "Velociraptor category", velociraptor.artifact_category);
    pushIf(rows, "Velociraptor parser status", velociraptor.parser_status);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "network" || category === "network") {
    pushIf(rows, "Artifact kind", network.artifact_type);
    pushIf(rows, "Interface name", network.interface_name);
    pushIf(rows, "Interface GUID", network.interface_guid);
    pushIf(rows, "Interface description", network.interface_description);
    pushIf(rows, "MAC", network.mac_address);
    pushIf(rows, "IPv4", network.ipv4 ?? network.ip_address);
    pushIf(rows, "IPv6", network.ipv6);
    pushIf(rows, "Gateway", network.gateway);
    pushIf(rows, "DNS servers", Array.isArray(network.dns_servers) ? network.dns_servers.join(" | ") : network.dns_servers);
    pushIf(rows, "Network profile", network.profile_name);
    pushIf(rows, "SSID", wlan.ssid);
    pushIf(rows, "BSSID", wlan.bssid);
    pushIf(rows, "Authentication", wlan.authentication);
    pushIf(rows, "Encryption", wlan.encryption);
    pushIf(rows, "DNS name", dns.name);
    pushIf(rows, "DNS type", dns.record_type);
    pushIf(rows, "DNS data", dns.data);
    pushIf(rows, "DNS IP", dns.ip);
    pushIf(rows, "Hostname", dns.name);
    pushIf(rows, "Flow", `${network.source_ip ?? "-"}:${network.source_port ?? "-"} -> ${network.destination_ip ?? "-"}:${network.destination_port ?? "-"}`);
    pushIf(rows, "Protocol", network.protocol);
    pushIf(rows, "State", network.state);
    pushIf(rows, "Process ID", network.process_id);
    pushIf(rows, "Process name", network.process_name ?? process.name);
    pushIf(rows, "Timestamp precision", event.timestamp_precision);
    pushIf(rows, "Timestamp interpretation", network.timestamp_interpretation);
    pushIf(rows, "Source file", network.source_file ?? dns.source_file ?? wlan.source_file ?? event.source_file);
    pushIf(rows, "Parser status", network.parser_status);
    pushIf(rows, "Velociraptor original path", velociraptor.original_path);
    pushIf(rows, "Velociraptor normalized path", velociraptor.normalized_windows_path);
    pushIf(rows, "Related domain", url.domain ?? network.domain);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (artifactType === "srum" && ["network", "application", "srum"].includes(category)) {
    pushIf(rows, "Artifact type", srum.artifact_type);
    pushIf(rows, "Table", srum.table);
    pushIf(rows, "Application", srum.app_name ?? srum.application ?? network.application ?? process.name);
    pushIf(rows, "App ID", srum.app_id);
    pushIf(rows, "Package", srum.package_name);
    pushIf(rows, "Process path", process.path);
    pushIf(rows, "User", user.name);
    pushIf(rows, "User SID", user.sid ?? srum.user_sid);
    pushIf(rows, "Bytes sent", network.bytes_sent ?? srum.bytes_sent);
    pushIf(rows, "Bytes received", network.bytes_received ?? srum.bytes_received);
    pushIf(rows, "Bytes total", network.bytes_total ?? srum.bytes_total);
    pushIf(rows, "Foreground sent", srum.foreground_bytes_sent);
    pushIf(rows, "Foreground received", srum.foreground_bytes_received);
    pushIf(rows, "Background sent", srum.background_bytes_sent);
    pushIf(rows, "Background received", srum.background_bytes_received);
    pushIf(rows, "Duration", srum.duration);
    pushIf(rows, "Connected time", srum.connected_time);
    pushIf(rows, "Energy usage", srum.energy_usage);
    pushIf(rows, "Cycle time", srum.cycle_time);
    pushIf(rows, "Interface LUID", srum.interface_luid);
    pushIf(rows, "Interface GUID", srum.interface_guid);
    pushIf(rows, "Interface profile", srum.interface_profile);
    pushIf(rows, "Network profile", srum.network_profile);
    pushIf(rows, "Source file", srum.source_file);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (category === "execution") {
    pushIf(rows, "Program", execution.program_name ?? process.name);
    pushIf(rows, "Command", process.command_line);
    pushIf(rows, "Path", file.path ?? process.path);
    pushIf(rows, "Run count", execution.run_count);
    pushIf(rows, "Last run", execution.last_run);
    pushIf(rows, "Source", execution.source);
  } else if (category === "logon" || category === "authentication" || category === "remote_access") {
    pushIf(rows, "User", user.name);
    pushIf(rows, "Host", host.name);
    pushIf(rows, "Event ID", windows.event_id);
    pushIf(rows, "Logon type", windows.logon_type);
    pushIf(rows, "Workstation", network.workstation_name);
    pushIf(rows, "Source IP", network.source_ip);
    pushIf(rows, "Channel", windows.channel);
    pushIf(rows, "Provider", windows.provider);
  } else if (category === "persistence" || category === "service" || category === "scheduled_task") {
    pushIf(rows, "Task name", task.name ?? windows.task_name);
    pushIf(rows, "Task path", task.path);
    pushIf(rows, "URI", task.uri);
    pushIf(rows, "Author", task.author);
    pushIf(rows, "Description", task.description);
    pushIf(rows, "Enabled", task.enabled);
    pushIf(rows, "Hidden", task.hidden);
    pushIf(rows, "RunAs / UserId", task.run_as ?? task.user_id);
    pushIf(rows, "Logon type", task.logon_type);
    pushIf(rows, "Run level", task.run_level);
    pushIf(rows, "Command", task.command ?? process.path);
    pushIf(rows, "Arguments", task.arguments);
    pushIf(rows, "Working directory", task.working_directory);
    pushIf(rows, "Action summary", task.action_summary);
    pushIf(rows, "Trigger summary", task.trigger_summary);
    pushIf(rows, "COM handler ClassId", task.com_handler_class_id);
    pushIf(rows, "Source file", task.source_file);
    pushIf(rows, "Path", file.path ?? process.path);
    pushIf(rows, "Process command line", process.command_line);
    pushIf(rows, "Service", windows.service_name);
    pushIf(rows, "Event ID", windows.event_id);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (category === "browser" || category === "web" || category === "file_transfer") {
    pushIf(rows, "Browser", browser.name ?? browser.browser);
    pushIf(rows, "Profile", browser.profile);
    pushIf(rows, "User", user.name);
    pushIf(rows, "Artifact type", browser.artifact_type);
    pushIf(rows, "Domain", url.domain ?? browser.domain);
    pushIf(rows, "URL", url.full ?? browser.url);
    pushIf(rows, "Final URL", browser.final_url);
    pushIf(rows, "Title", browser.title);
    pushIf(rows, "Search engine", browser.search_engine);
    pushIf(rows, "Search terms", browser.search_terms);
    pushIf(rows, "Visit count", browser.visit_count);
    pushIf(rows, "Typed count", browser.typed_count);
    pushIf(rows, "Referrer", browser.referrer);
    pushIf(rows, "Download target", download.target_path ?? file.path);
    pushIf(rows, "Filename", download.file_name ?? file.name);
    pushIf(rows, "MIME type", download.mime_type);
    pushIf(rows, "Size", download.total_bytes ?? file.size);
    pushIf(rows, "State", download.state ?? browser.download_state);
    pushIf(rows, "Danger type", browser.danger_type);
    pushIf(rows, "Interrupt reason", browser.interrupt_reason);
    pushIf(rows, "Source file", browser.source_file);
    pushIf(rows, "Original Velociraptor path", velociraptor.original_path);
  } else if (category === "file" || category === "file_access" || category === "filesystem") {
    pushIf(rows, "Path", file.path);
    pushIf(rows, "Name", file.name);
    pushIf(rows, "Extension", file.extension);
    pushIf(rows, "Parent path", file.parent_path);
    pushIf(rows, "Effective target", lnk.effective_path);
    pushIf(rows, "Effective target source", lnk.effective_path_source);
    pushIf(rows, "Display name", lnk.display_name);
    pushIf(rows, "JumpList application", jumplist.app_name);
    pushIf(rows, "JumpList AppID", jumplist.app_id);
    pushIf(rows, "JumpList AppID description", jumplist.app_id_description);
    pushIf(rows, "JumpList destination type", jumplist.destination_type);
    pushIf(rows, "JumpList entry number", jumplist.entry_number);
    pushIf(rows, "JumpList stream name", jumplist.stream_name);
    pushIf(rows, "JumpList interactions", jumplist.interaction_count);
    pushIf(rows, "JumpList DestList last accessed", jumplist.destlist_last_accessed);
    pushIf(rows, "JumpList DestList access count", jumplist.destlist_access_count);
    pushIf(rows, "JumpList DestList pin status", jumplist.destlist_pin_status);
    pushIf(rows, "Created", file.created);
    pushIf(rows, "Modified", file.modified);
    pushIf(rows, "Accessed", file.accessed);
    pushIf(rows, "MFT modified", file.mft_modified ?? file.changed);
    pushIf(rows, "Deleted", file.deleted);
    pushIf(rows, "In use", file.in_use);
    pushIf(rows, "Is directory", file.is_directory);
    pushIf(rows, "Attributes", file.attributes);
    pushIf(rows, "Has ADS", file.has_ads);
    pushIf(rows, "ADS", Array.isArray(file.ads) ? file.ads.join(" | ") : file.ads);
    pushIf(rows, "Size", file.size);
    pushIf(rows, "Filesystem source", filesystem.source);
    pushIf(rows, "Filesystem activity", filesystem.activity);
    pushIf(rows, "Filesystem reason", filesystem.reason);
    pushIf(rows, "Filesystem subtype", filesystem.artifact_type);
    pushIf(rows, "Deleted candidate", filesystem.is_deleted);
    pushIf(rows, "Path depth", filesystem.path_depth);
    pushIf(rows, "Suspicious path", filesystem.suspicious_path);
    pushIf(rows, "Timestomp suspected", filesystem.timestomp_suspected);
    pushIf(rows, "MFT entry", mft.entry_number);
    pushIf(rows, "Sequence", mft.sequence_number);
    pushIf(rows, "Reference", mft.reference_number);
    pushIf(rows, "Parent reference", mft.parent_reference_number);
    pushIf(rows, "MFT file attributes", mft.file_attributes);
    pushIf(rows, "MFT has ADS", mft.has_ads);
    pushIf(rows, "MFT ADS", Array.isArray(mft.ads) ? mft.ads.join(" | ") : mft.ads);
    pushIf(rows, "SI created", mft.si_created);
    pushIf(rows, "SI modified", mft.si_modified);
    pushIf(rows, "SI accessed", mft.si_accessed);
    pushIf(rows, "SI MFT modified", mft.si_mft_modified);
    pushIf(rows, "FN created", mft.fn_created);
    pushIf(rows, "FN modified", mft.fn_modified);
    pushIf(rows, "FN accessed", mft.fn_accessed);
    pushIf(rows, "FN MFT modified", mft.fn_mft_modified);
    pushIf(rows, "USN reason", usn.reason ?? usn.reasons);
    pushIf(rows, "USN", usn.usn);
    pushIf(rows, "USN timestamp", usn.timestamp);
    pushIf(rows, "USN file reference", usn.file_reference);
    pushIf(rows, "USN parent file reference", usn.parent_file_reference);
    pushIf(rows, "USN source info", usn.source_info);
    pushIf(rows, "Registry key", registry.key_path);
    pushIf(rows, "Registry value", registry.value_name);
    pushIf(rows, "Registry subtype", registry.artifact_type);
    pushIf(rows, "Shellbag path", shellbag.path);
    pushIf(rows, "Shellbag bag path", shellbag.bag_path);
    pushIf(rows, "Shellbag absolute path", shellbag.absolute_path);
    pushIf(rows, "Shell type", shellbag.shell_type);
    pushIf(rows, "Shellbag source file", shellbag.source_file);
    pushIf(rows, "Shellbag hive path", shellbag.hive_path);
    pushIf(rows, "Shellbag key path", shellbag.key_path);
    pushIf(rows, "Shellbag MRU", shellbag.mru_position ?? shellbag.mru);
    pushIf(rows, "Shellbag slot", shellbag.slot);
    pushIf(rows, "Shellbag node slot", shellbag.node_slot);
    pushIf(rows, "Shellbag last write", shellbag.last_write_time ?? shellbag.last_write);
    pushIf(rows, "Shellbag first interacted", shellbag.first_interacted);
    pushIf(rows, "Shellbag last interacted", shellbag.last_interacted);
    pushIf(rows, "Shellbag MFT entry", shellbag.mft_entry);
    pushIf(rows, "Shellbag MFT sequence", shellbag.mft_sequence);
    pushIf(rows, "Shellbag network", shellbag.is_network_path);
    pushIf(rows, "Shellbag USB", shellbag.is_usb_path);
    pushIf(rows, "Shellbag control panel", shellbag.is_control_panel);
    pushIf(rows, "Effective path", lnk.effective_path);
    pushIf(rows, "Effective path source", lnk.effective_path_source);
    pushIf(rows, "Display name", lnk.display_name);
    pushIf(rows, "Local path", lnk.local_path);
    pushIf(rows, "Shortcut target", lnk.target_path);
    pushIf(rows, "Target ID absolute path", lnk.target_id_absolute_path);
    pushIf(rows, "Relative path", lnk.relative_path);
    pushIf(rows, "Working directory", lnk.working_directory);
    pushIf(rows, "Arguments", lnk.arguments);
    pushIf(rows, "Description", lnk.description);
    pushIf(rows, "Icon location", lnk.icon_location);
    pushIf(rows, "Source LNK", lnk.source_file);
    pushIf(rows, "Machine ID", lnk.machine_id);
    pushIf(rows, "Drive type", lnk.drive_type);
    pushIf(rows, "Volume serial", lnk.drive_serial_number);
    pushIf(rows, "Volume label", lnk.volume_label);
    pushIf(rows, "Network path", lnk.network_path);
    pushIf(rows, "Share name", lnk.share_name);
    pushIf(rows, "Target created", lnk.target_created);
    pushIf(rows, "Target modified", lnk.target_modified);
    pushIf(rows, "Target accessed", lnk.target_accessed);
    pushIf(rows, "Source created", lnk.source_created);
    pushIf(rows, "Source modified", lnk.source_modified);
    pushIf(rows, "Source accessed", lnk.source_accessed);
    pushIf(rows, "Parse warnings", Array.isArray(lnk.parse_warnings) ? lnk.parse_warnings.join(" | ") : lnk.parse_warnings);
    pushIf(rows, "JumpList effective target", jumplist.effective_path);
    pushIf(rows, "JumpList effective target source", jumplist.effective_path_source);
    pushIf(rows, "JumpList local path", jumplist.local_path);
    pushIf(rows, "JumpList target", jumplist.target_path);
    pushIf(rows, "JumpList common path", jumplist.common_path);
    pushIf(rows, "JumpList relative path", jumplist.relative_path);
    pushIf(rows, "JumpList working directory", jumplist.working_directory);
    pushIf(rows, "JumpList arguments", jumplist.arguments);
    pushIf(rows, "JumpList source", jumplist.source_file);
    pushIf(rows, "Timestamp precision", event.timestamp_precision);
    pushIf(rows, "Timestamp interpretation", jumplist.timestamp_interpretation);
    pushIf(rows, "JumpList network path", jumplist.network_path);
    pushIf(rows, "JumpList share name", jumplist.share_name);
    pushIf(rows, "JumpList device name", jumplist.device_name);
    pushIf(rows, "JumpList drive type", jumplist.drive_type);
    pushIf(rows, "JumpList volume serial", jumplist.drive_serial_number);
    pushIf(rows, "JumpList volume label", jumplist.volume_label);
    pushIf(rows, "JumpList machine ID", jumplist.machine_id);
    pushIf(rows, "JumpList machine MAC", jumplist.machine_mac_address);
    pushIf(rows, "JumpList target created", jumplist.target_created);
    pushIf(rows, "JumpList target modified", jumplist.target_modified);
    pushIf(rows, "JumpList target accessed", jumplist.target_accessed);
    pushIf(rows, "JumpList tracker created", jumplist.tracker_created);
    pushIf(rows, "JumpList MFT entry", jumplist.mft_entry);
    pushIf(rows, "JumpList MFT sequence", jumplist.mft_sequence);
    pushIf(rows, "JumpList file attributes", jumplist.file_attributes);
    pushIf(rows, "JumpList parse method", jumplist.parse_method);
    pushIf(rows, "JumpList parse warnings", Array.isArray(jumplist.parse_warnings) ? jumplist.parse_warnings.join(" | ") : jumplist.parse_warnings);
    pushIf(rows, "Velociraptor original path", velociraptor.original_path);
    pushIf(rows, "Velociraptor normalized path", velociraptor.normalized_windows_path);
    pushIf(rows, "Velociraptor category", velociraptor.artifact_category);
    pushIf(rows, "Velociraptor parser status", velociraptor.parser_status);
    pushIf(rows, "Velociraptor collection ID", velociraptor.collection_id);
    pushIf(rows, "Network path", network.path);
    pushIf(rows, "Network share", network.share_name);
    pushIf(rows, "Network host", network.destination_hostname);
    pushIf(rows, "Drive letter", volume.drive_letter);
    pushIf(rows, "Volume GUID", volume.guid);
    pushIf(rows, "Volume serial", volume.serial);
    pushIf(rows, "Recycle Bin original path", recycleBin.original_path);
    pushIf(rows, "Recycle Bin original file", recycleBin.original_file_name);
    pushIf(rows, "Recycle Bin deleted time", recycleBin.deleted_time);
    pushIf(rows, "Recycle Bin SID", recycleBin.sid);
    pushIf(rows, "Recycle Bin $I path", recycleBin.i_file_path);
    pushIf(rows, "Recycle Bin $R path", recycleBin.r_file_path);
    pushIf(rows, "Recycle Bin pair ID", recycleBin.pair_id);
    pushIf(rows, "Recycle Bin has content", recycleBin.has_r_file);
  } else if (category === "registry") {
    pushIf(rows, "Subtype", registry.artifact_type);
    pushIf(rows, "Hive", registry.hive);
    pushIf(rows, "Hive path", registry.hive_path);
    pushIf(rows, "Key path", registry.key_path);
    pushIf(rows, "Value name", registry.value_name);
    pushIf(rows, "Value type", registry.value_type);
    pushIf(rows, "Value data", registry.value_data);
    pushIf(rows, "Last write", registry.last_write_time ?? registry.last_write);
    pushIf(rows, "Plugin", registry.plugin);
    pushIf(rows, "Batch", registry.batch);
    pushIf(rows, "User", user.name);
    pushIf(rows, "User SID", user.sid);
    pushIf(rows, "Process path", process.path);
    pushIf(rows, "Command", process.command_line);
    pushIf(rows, "Service", (event.service as Record<string, unknown> | undefined)?.name);
    pushIf(rows, "Service image path", (event.service as Record<string, unknown> | undefined)?.image_path);
    pushIf(rows, "Service DLL", (event.service as Record<string, unknown> | undefined)?.service_dll);
    pushIf(rows, "USB vendor", usb.vendor);
    pushIf(rows, "USB product", usb.product);
    pushIf(rows, "USB serial", usb.serial);
    pushIf(rows, "Drive letter", volume.drive_letter);
    pushIf(rows, "Volume GUID", volume.guid);
    pushIf(rows, "Destination", (event.destination as Record<string, unknown> | undefined)?.hostname);
    pushIf(rows, "Suspicious reasons", ((event.suspicious_reasons as string[] | undefined) ?? []).join(" | "));
  } else if (category === "windows_event" || windows.event_id) {
    pushIf(rows, "Event ID", windows.event_id);
    pushIf(rows, "Channel", windows.channel);
    pushIf(rows, "Provider", windows.provider);
    pushIf(rows, "Summary", eventMeta.message);
  }

  if (!rows.length) {
    pushIf(rows, "Summary", eventMeta.message);
    pushIf(rows, "Path", file.path);
    pushIf(rows, "Process", process.name);
    pushIf(rows, "URL", url.full ?? browser.url ?? network.url);
    pushIf(rows, "Registry key", registry.key_path);
    pushIf(rows, "SRUM application", srum.application);
  }

  return (
    <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">
      {rows.map(([label, value]) => (
        <div key={`${label}-${value}`} className="rounded-2xl border border-line bg-panel/40 px-3 py-2">
          <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-muted">{label}</p>
          <p className="mt-1 break-words text-sm text-ink">{value}</p>
        </div>
      ))}
    </div>
  );
}
