from __future__ import annotations

from typing import Any


def build_on_demand_module_registry(
    *,
    case_id: str | None,
    evidence_id: str | None,
    problematic_count: int = 0,
    indexed_docs: int = 0,
) -> dict[str, dict[str, Any]]:
    rules_available = indexed_docs > 0
    reports_available = indexed_docs > 0
    return {
        "rules": {
            "id": "rules",
            "label": "Run Sigma/YARA rules",
            "group": "on_demand",
            "module_category": "on_demand_stable",
            "status": "available" if rules_available else "disabled",
            "badge": "On-demand" if rules_available else "Needs indexed data",
            "requires": ["indexed_events"],
            "risk_level": "medium",
            "auto_runs": False,
            "visible_in_core": False,
            "visible_in_advanced": False,
            "route": "/rules",
            "case_route": f"/cases/{case_id}/rules" if case_id else None,
            "evidence_route": f"/evidences/{evidence_id}" if evidence_id else None,
            "description": "Runs rules against already indexed data. This does not reprocess evidence.",
            "disabled_reason": None if rules_available else "No indexed documents are available for this evidence yet.",
            "warning": "Does not run automatically. Executes only when launched manually.",
        },
        "reports": {
            "id": "reports",
            "label": "Generate report",
            "group": "on_demand",
            "module_category": "on_demand_stable",
            "status": "available" if reports_available else "disabled",
            "badge": "On-demand" if reports_available else "Needs indexed data",
            "requires": ["indexed_artifacts"],
            "risk_level": "medium",
            "auto_runs": False,
            "visible_in_core": False,
            "visible_in_advanced": False,
            "route": "/reports",
            "case_route": f"/cases/{case_id}/reports" if case_id else None,
            "evidence_route": f"/evidences/{evidence_id}" if evidence_id else None,
            "description": "Generate analyst-facing output after searchable data is already indexed.",
            "disabled_reason": None if reports_available else "No indexed documents are available for this evidence yet.",
            "warning": "Does not run automatically. Generates a bounded summary from current indexed data.",
        },
        "host_enrichment": {
            "id": "host_enrichment",
            "label": "Enrich hosts",
            "group": "on_demand",
            "module_category": "advanced",
            "status": "beta",
            "badge": "Advanced/Beta",
            "requires": ["indexed_artifacts"],
            "risk_level": "high",
            "auto_runs": False,
            "visible_in_core": False,
            "visible_in_advanced": True,
            "route": "/hosts",
            "case_route": f"/cases/{case_id}/hosts" if case_id else None,
            "description": "Optional host identity and context enrichment after ingest completes.",
            "warning": "May be slow. Use only when host context is needed beyond Search/Timeline.",
        },
        "deep_retry": {
            "id": "deep_retry",
            "label": "Deep retry problematic artifacts",
            "group": "on_demand",
            "module_category": "advanced",
            "status": "available" if problematic_count > 0 else "disabled",
            "badge": "Advanced/Beta" if problematic_count > 0 else "Needs problematic artifacts",
            "requires": ["problematic_artifacts"],
            "risk_level": "high",
            "auto_runs": False,
            "visible_in_core": False,
            "visible_in_advanced": True,
            "route": "/problematic-artifacts",
            "evidence_route": f"/evidences/{evidence_id}" if evidence_id else None,
            "description": "Retry only the artifacts that failed or were deferred, preserving the main ingest result.",
            "disabled_reason": None if problematic_count > 0 else "No problematic artifacts are available for deep retry.",
            "warning": "Potentially slow. Use only when the main ingest has already finished and you need deeper recovery.",
        },
        "benchmark": {
            "id": "benchmark",
            "label": "Benchmark & tuning",
            "group": "on_demand",
            "module_category": "advanced",
            "status": "advanced",
            "badge": "Advanced/Beta",
            "requires": ["admin"],
            "risk_level": "high",
            "auto_runs": False,
            "visible_in_core": False,
            "visible_in_advanced": True,
            "route": "/benchmarks",
            "evidence_route": f"/evidences/{evidence_id}" if evidence_id else None,
            "description": "Advanced benchmarking for test or demo evidence. Not part of the main ingest flow.",
            "warning": "May be slow and should only be used for test/demo evidence.",
        },
        "advanced_exports": {
            "id": "advanced_exports",
            "label": "Advanced debug export",
            "group": "on_demand",
            "module_category": "advanced",
            "status": "advanced",
            "badge": "Advanced",
            "requires": ["indexed_artifacts"],
            "risk_level": "medium",
            "auto_runs": False,
            "visible_in_core": False,
            "visible_in_advanced": True,
            "route": "/debug-export",
            "case_route": f"/cases/{case_id}/debug-export" if case_id else None,
            "description": "Export technical validation packs and low-level ingest diagnostics on demand.",
            "warning": "For debugging and validation. Not part of the main analyst workflow.",
        },
    }
