import { useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { RefreshCw, Sparkles } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { api, streamCaseAiChat, type AiStreamEvent } from "../../api/client";

// On-demand only: the assistant is never called automatically on page load.
// It has to go look (tools, not just the static case briefing), so keep this
// short enough to stay orienting rather than a full report.
const SUMMARY_PROMPT =
  "Give me a concise orientation summary of this case for an analyst opening it for the first time: what evidence has been collected, which hosts matter, what stands out (findings, high-risk activity, anything already flagged), and what you'd look at next. Use the tools to check rather than guessing. Keep it under 200 words.";

function SummaryMarkdown({ content }: { content: string }) {
  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        p: ({ children }) => <p className="mb-2 last:mb-0 leading-relaxed">{children}</p>,
        ul: ({ children }) => <ul className="mb-2 list-disc space-y-1 pl-4 last:mb-0">{children}</ul>,
        ol: ({ children }) => <ol className="mb-2 list-decimal space-y-1 pl-4 last:mb-0">{children}</ol>,
        strong: ({ children }) => <strong className="font-semibold text-ink">{children}</strong>,
        a: ({ href, children }) => (
          <a href={href} className="text-accent underline underline-offset-2" target="_blank" rel="noreferrer">
            {children}
          </a>
        ),
      }}
    >
      {content}
    </ReactMarkdown>
  );
}

export default function CaseSummaryCard({ caseId }: { caseId: string }) {
  const statusQuery = useQuery({ queryKey: ["ai-status"], queryFn: api.getAiStatus, staleTime: 60_000 });
  const [summary, setSummary] = useState("");
  const [streaming, setStreaming] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasRun, setHasRun] = useState(false);
  const abortRef = useRef<AbortController | null>(null);

  // No AI configured: render nothing rather than a dead button. The non-AI
  // build of the product must look and behave identically without this card.
  if (!statusQuery.data?.enabled) return null;

  async function summarize() {
    if (streaming) return;
    setHasRun(true);
    setSummary("");
    setError(null);
    setStreaming(true);
    const controller = new AbortController();
    abortRef.current = controller;
    try {
      await streamCaseAiChat(
        caseId,
        { messages: [{ role: "user", content: SUMMARY_PROMPT }] },
        (event: AiStreamEvent) => {
          if (event.type === "text" && event.text) {
            setSummary((current) => current + event.text);
          } else if (event.type === "error" && event.text) {
            setError(event.text);
          }
        },
        controller.signal,
      );
    } catch (err) {
      if (!controller.signal.aborted) {
        setError(err instanceof Error ? err.message : "The assistant failed to answer.");
      }
    } finally {
      setStreaming(false);
      abortRef.current = null;
    }
  }

  return (
    <section className="rounded-[28px] border border-line bg-panel/70 p-6 shadow-panel" data-testid="case-summary-card">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Sparkles size={16} className="text-accent" />
          <p className="font-mono text-xs uppercase tracking-[0.24em] text-accent">AI case summary</p>
        </div>
        <button
          type="button"
          onClick={() => void summarize()}
          disabled={streaming}
          className="inline-flex items-center gap-2 rounded-xl border border-line bg-abyss px-3 py-2 text-sm text-ink hover:border-accent/60 disabled:cursor-not-allowed disabled:opacity-60"
        >
          <RefreshCw size={14} className={streaming ? "animate-spin" : ""} />
          {streaming ? "Summarizing…" : hasRun ? "Regenerate" : "Summarize case"}
        </button>
      </div>
      {hasRun ? (
        <div className="mt-4 rounded-2xl border border-line/70 bg-abyss/40 p-4 text-sm text-muted" data-testid="case-summary-content">
          {error ? (
            <p className="text-danger">{error}</p>
          ) : summary ? (
            <SummaryMarkdown content={summary} />
          ) : (
            <p>Thinking…</p>
          )}
          <p className="mt-3 border-t border-line/60 pt-3 text-[11px] uppercase tracking-[0.14em] text-muted/70">
            Generated by AI -- verify before relying on it.
          </p>
        </div>
      ) : null}
    </section>
  );
}
