#!/usr/bin/env bash
set -euo pipefail

# Kairon DFIR first-run setup wizard.
# Usage: bash scripts/setup.sh          (interactive)
#        bash scripts/setup.sh --help
#
# Non-interactive examples:
#   bash scripts/setup.sh --mode localhost --no-memory --no-dashboards
#   bash scripts/setup.sh --mode https --url https://dfir.example.com --admin-user admin --admin-email admin@example.com

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

DEPLOYMENT_MODE=""
PUBLIC_URL=""
AUTH_ENABLED="true"
ENABLE_MEMORY="false"
ENABLE_DASHBOARDS="false"
BOOTSTRAP_ADMIN_USERNAME=""
BOOTSTRAP_ADMIN_EMAIL=""
INTERACTIVE=true

usage() {
  cat <<'EOF'
Kairon DFIR setup — creates .env with secrets and configuration.

Usage: bash scripts/setup.sh [OPTIONS]

  Run without options for interactive mode.

Options:
  --non-interactive        Run without prompts (requires --mode and --url).
  --mode MODE              Deployment mode: localhost, lan, https.
  --url URL                Public URL (e.g. http://localhost:5173).
  --no-auth                Disable authentication (not recommended).
  --memory                 Enable memory analysis feature.
  --dashboards             Enable OpenSearch Dashboards.
  --admin-user USERNAME    Bootstrap admin username.
  --admin-email EMAIL      Bootstrap admin email.
  --debug                  Write generated secrets to stdout.
  -h, --help               Show this message.
EOF
  exit 0
}

generate_secret() {
  openssl rand -hex 32
}

check_prerequisites() {
  local missing=()
  for cmd in docker openssl python3; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
      missing+=("$cmd")
    fi
  done

  if ! docker compose version >/dev/null 2>&1; then
    missing+=("docker compose (v2)")
  fi

  if [[ "${#missing[@]}" -gt 0 ]]; then
    echo "Missing prerequisites: ${missing[*]}" >&2
    echo "Install them and re-run this script." >&2
    exit 1
  fi
}

write_env() {
  local env_file="$ROOT_DIR/.env"
  local timestamp
  timestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  # Derive mode-specific defaults
  local derived_url="$PUBLIC_URL"
  if [[ -z "$derived_url" ]]; then
    case "$DEPLOYMENT_MODE" in
      localhost) derived_url="http://localhost:5173" ;;
      lan)       derived_url="http://localhost:5173" ;;
      https)     derived_url="https://localhost" ;;
      *)         derived_url="http://localhost:5173" ;;
    esac
  fi

  if [[ "$DEPLOYMENT_MODE" == "https" ]]; then
    derived_url="${derived_url%/}"
    if [[ ! "$derived_url" =~ ^https:// ]]; then
      echo "WARNING: HTTPS mode selected but public URL does not start with https://" >&2
      echo "         You should configure an HTTPS reverse proxy and update KAIRON_PUBLIC_URL." >&2
    fi
  fi

  echo "# Kairon DFIR environment — generated by scripts/setup.sh at ${timestamp}" > "$env_file"
  echo "# Deployment mode: ${DEPLOYMENT_MODE}" >> "$env_file"
  echo "" >> "$env_file"

  cat >> "$env_file" <<-ENVEOF
KAIRON_DEPLOYMENT_MODE=${DEPLOYMENT_MODE}
KAIRON_PUBLIC_URL=${derived_url}
KAIRON_AUTH_ENABLED=${AUTH_ENABLED}

# ---- Secrets (auto-generated) ----
KAIRON_SESSION_SECRET=$(generate_secret)
KAIRON_CSRF_SECRET=$(generate_secret)
POSTGRES_PASSWORD=$(generate_secret)
OPENSEARCH_INITIAL_ADMIN_PASSWORD=$(generate_secret)

# ---- Optional bootstrap admin (prefer CLI: python -m app.cli create-admin) ----
KAIRON_BOOTSTRAP_ADMIN_USERNAME=${BOOTSTRAP_ADMIN_USERNAME}
KAIRON_BOOTSTRAP_ADMIN_EMAIL=${BOOTSTRAP_ADMIN_EMAIL}
KAIRON_BOOTSTRAP_ADMIN_PASSWORD=

# ---- Optional features ----
KAIRON_ENABLE_MEMORY=${ENABLE_MEMORY}
KAIRON_ENABLE_DASHBOARDS=${ENABLE_DASHBOARDS}

# ---- Advanced overrides (see config/defaults.env for all defaults) ----
# POSTGRES_HOST=postgres
# REDIS_URL=redis://redis:6379/0
# BACKEND_LOG_LEVEL=INFO
ENVEOF

  chmod 600 "$env_file"

  echo ""
  echo "=== .env file written ==="
  echo "  Path:  $env_file"
  echo "  Mode:  $DEPLOYMENT_MODE"
  echo "  URL:   $derived_url"
  echo "  Auth:  $AUTH_ENABLED"
  echo "  Memory:  $ENABLE_MEMORY"
  echo "  Dashboards:  $ENABLE_DASHBOARDS"
  if [[ -n "$BOOTSTRAP_ADMIN_USERNAME" ]]; then
    echo "  Admin user:  $BOOTSTRAP_ADMIN_USERNAME"
    if [[ -n "$BOOTSTRAP_ADMIN_EMAIL" ]]; then
      echo "  Admin email: $BOOTSTRAP_ADMIN_EMAIL"
    fi
  fi

  local secrets_list
  secrets_list="$(grep -E '^(KAIRON_SESSION_SECRET|KAIRON_CSRF_SECRET|POSTGRES_PASSWORD|OPENSEARCH_INITIAL_ADMIN_PASSWORD)=' "$env_file" | sed 's/=.*/=******/')"
  echo ""
  echo "=== Next steps ==="
  echo "  1. Review .env:  cat $env_file"
  echo "  2. (Optional) Create admin:  docker compose run --rm backend python -m app.cli create-admin"
  echo "  3. Start services:  docker compose up -d"
  echo "  4. Open browser:  $derived_url"
  echo ""
  echo "  For memory analysis, start with: docker compose --profile memory up -d"
  echo "  For dashboards:   http://localhost:5601"
}

interactive_mode() {
  echo "=== Kairon DFIR First-Run Setup ==="
  echo ""

  # Deployment mode
  echo "Select deployment mode:"
  echo "  1) localhost — single developer machine (default)"
  echo "  2) lan — local network access from other machines"
  echo "  3) https — production with HTTPS reverse proxy"
  read -r -p "Choice [1]: " mode_choice
  case "${mode_choice:-1}" in
    1) DEPLOYMENT_MODE="localhost" ;;
    2) DEPLOYMENT_MODE="lan" ;;
    3) DEPLOYMENT_MODE="https" ;;
    *) DEPLOYMENT_MODE="localhost" ;;
  esac
  echo "  Selected: $DEPLOYMENT_MODE"
  echo ""

  # Public URL
  local default_url
  case "$DEPLOYMENT_MODE" in
    localhost) default_url="http://localhost:5173" ;;
    lan)       default_url="http://localhost:5173" ;;
    https)     default_url="https://localhost" ;;
  esac
  read -r -p "Public URL [$default_url]: " url_input
  PUBLIC_URL="${url_input:-$default_url}"
  echo "  Public URL: $PUBLIC_URL"
  echo ""

  # Auth
  read -r -p "Enable authentication? [Y/n]: " auth_input
  case "${auth_input:-y}" in
    [Nn]*) AUTH_ENABLED="false" ;;
    *)     AUTH_ENABLED="true" ;;
  esac
  echo "  Authentication: $AUTH_ENABLED"
  echo ""

  # Optional features
  read -r -p "Enable memory analysis? [y/N]: " mem_input
  case "${mem_input:-n}" in
    [Yy]*) ENABLE_MEMORY="true" ;;
    *)    ENABLE_MEMORY="false" ;;
  esac
  echo "  Memory analysis: $ENABLE_MEMORY"
  echo ""

  read -r -p "Enable OpenSearch Dashboards? [y/N]: " dash_input
  case "${dash_input:-n}" in
    [Yy]*) ENABLE_DASHBOARDS="true" ;;
    *)    ENABLE_DASHBOARDS="false" ;;
  esac
  echo "  Dashboards: $ENABLE_DASHBOARDS"
  echo ""

  # Admin credentials
  echo "--- Bootstrap Admin (optional) ---"
  echo "Note: Admin password is NOT saved to .env."
  echo "      Create the admin later with: docker compose run --rm backend python -m app.cli create-admin"
  read -r -p "Bootstrap admin username (leave blank to skip): " admin_user
  if [[ -n "$admin_user" ]]; then
    BOOTSTRAP_ADMIN_USERNAME="$admin_user"
    read -r -p "Bootstrap admin email: " admin_email
    BOOTSTRAP_ADMIN_EMAIL="$admin_email"
  fi
  echo ""
}

non_interactive_mode() {
  if [[ -z "$DEPLOYMENT_MODE" ]]; then
    echo "Error: --mode is required in non-interactive mode." >&2
    echo "Valid modes: localhost, lan, https" >&2
    exit 2
  fi

  case "$DEPLOYMENT_MODE" in
    localhost|lan|https) ;;
    *)
      echo "Error: Invalid deployment mode '$DEPLOYMENT_MODE'. Valid: localhost, lan, https" >&2
      exit 2
      ;;
  esac
}

check_existing_env() {
  local env_file="$ROOT_DIR/.env"
  if [[ -f "$env_file" ]]; then
    echo "WARNING: $env_file already exists." >&2
    if [[ "$INTERACTIVE" == true ]]; then
      read -r -p "Overwrite? [y/N]: " overwrite
      case "${overwrite:-n}" in
        [Yy]*) return 0 ;;
        *) echo "Aborted."; exit 0 ;;
      esac
    else
      echo "Pass --non-interactive to overwrite, or remove the existing .env first." >&2
      exit 1
    fi
  fi
}

# ---- Argument parsing ----
while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive) INTERACTIVE=false; shift ;;
    --mode) DEPLOYMENT_MODE="$2"; shift 2 ;;
    --url) PUBLIC_URL="$2"; shift 2 ;;
    --no-auth) AUTH_ENABLED="false"; shift ;;
    --memory) ENABLE_MEMORY="true"; shift ;;
    --dashboards) ENABLE_DASHBOARDS="true"; shift ;;
    --admin-user) BOOTSTRAP_ADMIN_USERNAME="$2"; shift 2 ;;
    --admin-email) BOOTSTRAP_ADMIN_EMAIL="$2"; shift 2 ;;
    --debug)
      echo "=== Debug: secrets will NOT be generated ==="
      generate_secret() { echo "DEBUG_SECRET_$(openssl rand -hex 4)"; }
      shift
      ;;
    -h|--help) usage ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

check_prerequisites || true

if [[ "$INTERACTIVE" == true ]]; then
  check_existing_env
  interactive_mode
else
  if [[ -f "$ROOT_DIR/.env" ]]; then
    echo "Non-interactive mode: overwriting existing .env" >&2
  fi
  non_interactive_mode
fi

write_env
