from __future__ import annotations

from copy import deepcopy
from typing import Any


CAPABILITY_KEYS = [
    "supportsTimeline",
    "supportsSearch",
    "supportsProcesses",
    "supportsNetwork",
    "supportsPersistence",
    "supportsRegistry",
    "supportsJournal",
    "supportsMemory",
    "supportsPackages",
    "supportsServices",
    "supportsUsers",
    "supportsFilesystem",
    "supportsBrowser",
    "supportsCloud",
    "supportsEmail",
]


ARTIFACT_REGISTRY: dict[str, dict[str, Any]] = {
    "evtx": {
        "id": "evtx",
        "label": "Windows Events",
        "platforms": ["windows"],
        "aliases": ["windows_event"],
        "category": "logs",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "scroll-text",
        "parser": "evtxecmd_csv",
        "normalizer": "normalize_windows_event",
        "view": "evtx",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["event_id", "provider", "channel", "computer"],
        "quick_selects": ["event_logs", "execution"],
        "capabilities": ["supportsTimeline", "supportsSearch"],
    },
    "powershell": {
        "id": "powershell",
        "label": "PowerShell",
        "platforms": ["windows"],
        "aliases": [],
        "category": "execution",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "terminal-square",
        "parser": "powershell_history",
        "normalizer": "normalize_powershell_record",
        "view": "powershell",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["command", "source_file", "artifact_type"],
        "quick_selects": [],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsProcesses"],
    },
    "prefetch": {
        "id": "prefetch",
        "label": "Prefetch",
        "platforms": ["windows"],
        "aliases": [],
        "category": "execution",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "rocket",
        "parser": "prefetch_raw",
        "normalizer": "normalize_prefetch_entry",
        "view": "execution",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier1",
        "filter_fields": ["executable", "run_count", "path"],
        "quick_selects": ["execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsProcesses"],
    },
    "shimcache": {
        "id": "shimcache",
        "label": "Shimcache",
        "platforms": ["windows"],
        "aliases": ["appcompat"],
        "category": "execution",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "file-scan",
        "parser": "shimcache_raw",
        "normalizer": "normalize_shimcache_entry",
        "view": "execution_artifacts",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier1",
        "filter_fields": ["path", "program", "hash"],
        "quick_selects": ["execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsProcesses"],
    },
    "amcache": {
        "id": "amcache",
        "label": "Amcache",
        "platforms": ["windows"],
        "aliases": [],
        "category": "execution",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "archive",
        "parser": "amcache_raw",
        "normalizer": "normalize_amcache_entry",
        "view": "execution_artifacts",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier1",
        "filter_fields": ["path", "program", "hash"],
        "quick_selects": ["execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsProcesses"],
    },
    "lnk": {
        "id": "lnk",
        "label": "LNK",
        "platforms": ["windows"],
        "aliases": [],
        "category": "execution",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "link",
        "parser": "lnk_raw",
        "normalizer": "normalize_lnk_entry",
        "view": "execution",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier1",
        "filter_fields": ["target_path", "arguments", "working_dir"],
        "quick_selects": ["execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsProcesses"],
    },
    "jumplist": {
        "id": "jumplist",
        "label": "Jump Lists",
        "platforms": ["windows"],
        "aliases": [],
        "category": "execution",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "list-tree",
        "parser": "jumplist_automatic",
        "normalizer": "normalize_jumplist_entry",
        "view": "jumplist",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier1",
        "filter_fields": ["target_path", "arguments", "source_file", "app_id"],
        "quick_selects": ["execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsProcesses"],
    },
    "browser": {
        "id": "browser",
        "label": "Browser",
        "platforms": ["windows", "linux"],
        "aliases": [],
        "category": "browser",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "globe",
        "parser": "browser_chromium_history",
        "normalizer": "normalize_browser_record",
        "view": "browser",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier1",
        "filter_fields": ["url", "domain", "title", "profile"],
        "quick_selects": [],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsBrowser"],
    },
    "service": {
        "id": "service",
        "label": "Services",
        "platforms": ["windows"],
        "aliases": ["services"],
        "category": "persistence",
        "group_id": "windows_persistence",
        "group_label": "Windows Persistence",
        "icon": "cog",
        "parser": "windows_service_registry",
        "normalizer": "normalize_service_entry",
        "view": "persistence",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["service_name", "image_path", "display_name"],
        "quick_selects": ["persistence"],
        "capabilities": ["supportsSearch", "supportsPersistence", "supportsServices"],
    },
    "scheduled_task": {
        "id": "scheduled_task",
        "label": "Scheduled Tasks",
        "platforms": ["windows"],
        "aliases": ["scheduled_tasks"],
        "category": "persistence",
        "group_id": "windows_persistence",
        "group_label": "Windows Persistence",
        "icon": "calendar-clock",
        "parser": "scheduled_task_xml",
        "normalizer": "normalize_scheduled_task_entry",
        "view": "persistence",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["task_name", "command", "arguments"],
        "quick_selects": ["persistence"],
        "capabilities": ["supportsSearch", "supportsPersistence", "supportsServices"],
    },
    "registry": {
        "id": "registry",
        "label": "Registry",
        "platforms": ["windows", "memory"],
        "aliases": ["registry_event", "registry_command"],
        "category": "persistence",
        "group_id": "windows_persistence",
        "group_label": "Windows Persistence",
        "icon": "database",
        "parser": "registry_usb",
        "normalizer": "normalize_registry_entry",
        "view": "registry",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["hive", "key_path", "value_name"],
        "quick_selects": ["persistence"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsRegistry", "supportsPersistence"],
    },
    "defender": {
        "id": "defender",
        "label": "Defender",
        "platforms": ["windows"],
        "aliases": [],
        "category": "security",
        "group_id": "windows_persistence",
        "group_label": "Windows Persistence",
        "icon": "shield",
        "parser": "defender_evtx",
        "normalizer": "normalize_defender_record",
        "view": "defender",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier2",
        "filter_fields": [],
        "quick_selects": ["persistence"],
        "capabilities": ["supportsTimeline", "supportsSearch"],
    },
    "usb": {
        "id": "usb",
        "label": "USB",
        "platforms": ["windows"],
        "aliases": [],
        "category": "device",
        "group_id": "windows_persistence",
        "group_label": "Windows Persistence",
        "icon": "usb",
        "parser": "registry_usb",
        "normalizer": "normalize_usb_entry",
        "view": "usb",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier1",
        "filter_fields": ["vendor", "product", "serial", "device_instance_id"],
        "quick_selects": [],
        "capabilities": ["supportsTimeline", "supportsSearch"],
    },
    "recycle_bin": {
        "id": "recycle_bin",
        "label": "Recycle Bin",
        "platforms": ["windows"],
        "aliases": [],
        "category": "filesystem",
        "group_id": "windows_persistence",
        "group_label": "Windows Persistence",
        "icon": "trash-2",
        "parser": "recycle_bin",
        "normalizer": "normalize_recycle_bin_entry",
        "view": "recycle_bin",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier2",
        "filter_fields": [],
        "quick_selects": [],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsFilesystem"],
    },
    "linux_journal": {
        "id": "linux_journal",
        "label": "Journal",
        "platforms": ["linux"],
        "aliases": [],
        "category": "logs",
        "group_id": "linux_logs",
        "group_label": "Linux Logs",
        "icon": "scroll-text",
        "parser": "linux_journal_raw",
        "normalizer": "normalize_linux_row",
        "view": "evtx",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["linux.username", "linux.process", "linux.hostname", "linux.event_action"],
        "quick_selects": ["core_logs", "execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsJournal"],
    },
    "linux_auth": {
        "id": "linux_auth",
        "label": "Auth logs",
        "platforms": ["linux"],
        "aliases": [],
        "category": "logs",
        "group_id": "linux_logs",
        "group_label": "Linux Logs",
        "icon": "shield-check",
        "parser": "linux_auth_raw",
        "normalizer": "normalize_linux_row",
        "view": "network",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["linux.username", "linux.event_action", "linux.source_ip", "linux.hostname"],
        "quick_selects": ["core_logs", "execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsJournal", "supportsUsers", "supportsNetwork"],
    },
    "linux_syslog": {
        "id": "linux_syslog",
        "label": "Syslog",
        "platforms": ["linux"],
        "aliases": [],
        "category": "logs",
        "group_id": "linux_logs",
        "group_label": "Linux Logs",
        "icon": "scroll",
        "parser": "linux_syslog_raw",
        "normalizer": "normalize_linux_row",
        "view": "network",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["linux.username", "linux.process", "linux.hostname"],
        "quick_selects": ["core_logs", "execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsJournal", "supportsNetwork"],
    },
    "linux_audit": {
        "id": "linux_audit",
        "label": "Audit logs",
        "platforms": ["linux"],
        "aliases": [],
        "category": "logs",
        "group_id": "linux_logs",
        "group_label": "Linux Logs",
        "icon": "file-warning",
        "parser": "linux_audit_raw",
        "normalizer": "normalize_linux_row",
        "view": "network",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["linux.username", "linux.command", "linux.pid", "linux.event_action"],
        "quick_selects": ["core_logs", "execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsJournal", "supportsProcesses"],
    },
    "linux_apache": {
        "id": "linux_apache",
        "label": "Apache Logs",
        "platforms": ["linux"],
        "aliases": [],
        "category": "logs",
        "group_id": "linux_logs",
        "group_label": "Linux Logs",
        "icon": "file-text",
        "parser": "linux_apache_raw",
        "normalizer": "normalize_linux_row",
        "view": "network",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["linux.source_ip", "linux.http_method", "linux.http_status", "linux.url_path", "linux.http_user_agent"],
        "quick_selects": ["core_logs", "network"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsNetwork"],
    },
    "linux_shell_history": {
        "id": "linux_shell_history",
        "label": "Bash History",
        "platforms": ["linux"],
        "aliases": [],
        "category": "execution",
        "group_id": "linux_logs",
        "group_label": "Linux Logs",
        "icon": "terminal",
        "parser": "linux_shell_raw",
        "normalizer": "normalize_linux_row",
        "view": "execution",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier1",
        "filter_fields": ["linux.command", "linux.username", "linux.hostname"],
        "quick_selects": ["execution"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsProcesses", "supportsUsers"],
    },
    "linux_cron": {
        "id": "linux_cron",
        "label": "Cron",
        "platforms": ["linux"],
        "aliases": [],
        "category": "persistence",
        "group_id": "linux_persistence",
        "group_label": "Linux Persistence",
        "icon": "calendar-clock",
        "parser": "linux_cron_raw",
        "normalizer": "normalize_linux_row",
        "view": "persistence",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": ["linux.command", "linux.username", "linux.hostname"],
        "quick_selects": ["persistence"],
        "capabilities": ["supportsSearch", "supportsPersistence", "supportsServices"],
    },
    "linux_systemd": {
        "id": "linux_systemd",
        "label": "Systemd Units",
        "platforms": ["linux"],
        "aliases": [],
        "category": "persistence",
        "group_id": "linux_persistence",
        "group_label": "Linux Persistence",
        "icon": "cog",
        "parser": "linux_systemd_raw",
        "normalizer": "normalize_linux_row",
        "view": "persistence",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": True,
        "usable_tier": "tier2",
        "filter_fields": ["linux.command", "linux.process", "linux.hostname"],
        "quick_selects": ["execution", "persistence"],
        "capabilities": ["supportsSearch", "supportsPersistence", "supportsServices"],
    },
    "linux_ssh": {
        "id": "linux_ssh",
        "label": "SSH",
        "platforms": ["linux"],
        "aliases": [],
        "category": "persistence",
        "group_id": "linux_persistence",
        "group_label": "Linux Persistence",
        "icon": "key-round",
        "parser": "linux_ssh_raw",
        "normalizer": "normalize_linux_row",
        "view": "network",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": True,
        "usable_tier": "tier2",
        "filter_fields": ["linux.username", "linux.event_action", "linux.hostname"],
        "quick_selects": ["persistence"],
        "capabilities": ["supportsSearch", "supportsPersistence", "supportsUsers", "supportsNetwork"],
    },
    "linux_identity": {
        "id": "linux_identity",
        "label": "Users / Groups",
        "platforms": ["linux"],
        "aliases": [],
        "category": "identity",
        "group_id": "linux_inventory",
        "group_label": "Linux Inventory",
        "icon": "users",
        "parser": "linux_identity_raw",
        "normalizer": "normalize_linux_row",
        "view": "auto",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": False,
        "usable_tier": "tier2",
        "filter_fields": ["linux.username", "linux.hostname"],
        "quick_selects": ["persistence"],
        "capabilities": ["supportsSearch", "supportsUsers"],
    },
    "linux_sudoers": {
        "id": "linux_sudoers",
        "label": "Sudoers",
        "platforms": ["linux"],
        "aliases": [],
        "category": "persistence",
        "group_id": "linux_persistence",
        "group_label": "Linux Persistence",
        "icon": "shield-ellipsis",
        "parser": "linux_sudoers_raw",
        "normalizer": "normalize_linux_row",
        "view": "persistence",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": True,
        "usable_tier": "tier2",
        "filter_fields": ["linux.username", "linux.command", "linux.hostname"],
        "quick_selects": ["persistence"],
        "capabilities": ["supportsSearch", "supportsPersistence", "supportsUsers"],
    },
    "linux_packages": {
        "id": "linux_packages",
        "label": "Packages",
        "platforms": ["linux"],
        "aliases": [],
        "category": "inventory",
        "group_id": "linux_inventory",
        "group_label": "Linux Inventory",
        "icon": "package",
        "parser": "linux_packages_raw",
        "normalizer": "normalize_linux_row",
        "view": "auto",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier1",
        "filter_fields": ["linux.command", "linux.hostname"],
        "quick_selects": [],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsPackages"],
    },
    "linux_network": {
        "id": "linux_network",
        "label": "Network",
        "platforms": ["linux"],
        "aliases": ["network"],
        "category": "inventory",
        "group_id": "linux_inventory",
        "group_label": "Linux Inventory",
        "icon": "network",
        "parser": "linux_network_raw",
        "normalizer": "normalize_linux_row",
        "view": "network",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier2",
        "filter_fields": ["linux.hostname", "linux.source_ip"],
        "quick_selects": [],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsNetwork"],
    },
    "linux_os_info": {
        "id": "linux_os_info",
        "label": "OS Info",
        "platforms": ["linux"],
        "aliases": [],
        "category": "inventory",
        "group_id": "linux_inventory",
        "group_label": "Linux Inventory",
        "icon": "monitor",
        "parser": "linux_os_info_raw",
        "normalizer": "normalize_linux_row",
        "view": "auto",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": False,
        "usable_tier": "tier2",
        "filter_fields": ["linux.hostname", "host.name"],
        "quick_selects": [],
        "capabilities": ["supportsSearch", "supportsUsers"],
    },
    "mft": {
        "id": "mft",
        "label": "MFT / Filesystem",
        "platforms": ["windows"],
        "aliases": ["ntfs", "usn"],
        "category": "filesystem",
        "group_id": "windows_persistence",
        "group_label": "Windows Persistence",
        "icon": "folder-tree",
        "parser": "mft_raw",
        "normalizer": "normalize_mft_entry",
        "view": "filesystem",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier2",
        "filter_fields": ["file.path", "file.name"],
        "quick_selects": [],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsFilesystem"],
    },
    "cloud_sync": {
        "id": "cloud_sync",
        "label": "Cloud Sync",
        "platforms": ["windows"],
        "aliases": ["cloud"],
        "category": "cloud",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "cloud",
        "parser": "cloud_sync",
        "normalizer": "normalize_cloud_sync_entry",
        "view": "cloud_sync",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": False,
        "usable_tier": "tier2",
        "filter_fields": [],
        "quick_selects": [],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsCloud"],
    },
    "email": {
        "id": "email",
        "label": "Email",
        "platforms": ["windows", "linux"],
        "aliases": [],
        "category": "email",
        "group_id": "windows_core",
        "group_label": "Windows Core",
        "icon": "mail",
        "parser": "email_artifacts",
        "normalizer": "normalize_email_entry",
        "view": "auto",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier2",
        "filter_fields": [],
        "quick_selects": [],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsEmail"],
    },
    "process": {
        "id": "process",
        "label": "Processes",
        "platforms": ["memory"],
        "aliases": [],
        "category": "memory",
        "group_id": "memory_core",
        "group_label": "Memory Core",
        "icon": "binary",
        "parser": "memory_processes",
        "normalizer": "normalize_memory_process",
        "view": "execution",
        "searchable": True,
        "timeline_capable": True,
        "severity_support": True,
        "usable_tier": "tier1",
        "filter_fields": [],
        "quick_selects": ["memory_core"],
        "capabilities": ["supportsTimeline", "supportsSearch", "supportsProcesses", "supportsMemory"],
    },
    "vads": {
        "id": "vads",
        "label": "VADs",
        "platforms": ["memory"],
        "aliases": ["vad"],
        "category": "memory",
        "group_id": "memory_core",
        "group_label": "Memory Core",
        "icon": "layout-panel-top",
        "parser": "memory_vads",
        "normalizer": "normalize_memory_vad",
        "view": "auto",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": True,
        "usable_tier": "tier2",
        "filter_fields": [],
        "quick_selects": ["memory_core"],
        "capabilities": ["supportsSearch", "supportsMemory", "supportsProcesses"],
    },
    "dlls": {
        "id": "dlls",
        "label": "DLLs",
        "platforms": ["memory"],
        "aliases": ["dll"],
        "category": "memory",
        "group_id": "memory_core",
        "group_label": "Memory Core",
        "icon": "library",
        "parser": "memory_dlls",
        "normalizer": "normalize_memory_dll",
        "view": "auto",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": True,
        "usable_tier": "tier2",
        "filter_fields": [],
        "quick_selects": ["memory_core"],
        "capabilities": ["supportsSearch", "supportsMemory", "supportsProcesses"],
    },
    "handles": {
        "id": "handles",
        "label": "Handles",
        "platforms": ["memory"],
        "aliases": [],
        "category": "memory",
        "group_id": "memory_core",
        "group_label": "Memory Core",
        "icon": "grip",
        "parser": "memory_handles",
        "normalizer": "normalize_memory_handle",
        "view": "auto",
        "searchable": True,
        "timeline_capable": False,
        "severity_support": True,
        "usable_tier": "tier2",
        "filter_fields": [],
        "quick_selects": ["memory_core"],
        "capabilities": ["supportsSearch", "supportsMemory"],
    },
}


_ARTIFACT_ALIAS_LOOKUP: dict[str, str] = {}
for entry_key, entry in ARTIFACT_REGISTRY.items():
    _ARTIFACT_ALIAS_LOOKUP[entry_key] = entry_key
    for alias in entry.get("aliases") or []:
        _ARTIFACT_ALIAS_LOOKUP[str(alias).strip().lower()] = entry_key


def capability_flags(capabilities: list[str] | tuple[str, ...] | set[str] | None = None) -> dict[str, bool]:
    selected = {str(item).strip() for item in (capabilities or []) if str(item).strip()}
    return {key: key in selected for key in CAPABILITY_KEYS}


def canonical_artifact_family(value: object | None) -> str:
    normalized = str(value or "").strip().lower()
    if not normalized:
        return ""
    return _ARTIFACT_ALIAS_LOOKUP.get(normalized, normalized)


def artifact_registry_entry(value: object | None) -> dict[str, Any]:
    canonical = canonical_artifact_family(value)
    if not canonical:
        return {
            "id": "",
            "label": "",
            "platforms": [],
            "aliases": [],
            "category": "other",
            "group_id": "other",
            "group_label": "Other",
            "icon": "file",
            "parser": None,
            "normalizer": None,
            "view": "auto",
            "searchable": False,
            "timeline_capable": False,
            "severity_support": False,
            "usable_tier": "tier2",
            "filter_fields": [],
            "quick_selects": [],
            "capabilities": capability_flags([]),
        }
    entry = deepcopy(ARTIFACT_REGISTRY.get(canonical) or {})
    entry["capabilities"] = capability_flags(entry.get("capabilities"))
    return entry


def artifact_registry_entries(*, platforms: list[str] | None = None) -> list[dict[str, Any]]:
    selected_platforms = {str(item).strip().lower() for item in (platforms or []) if str(item).strip()}
    entries = []
    for key in sorted(ARTIFACT_REGISTRY):
        entry = artifact_registry_entry(key)
        if selected_platforms and not selected_platforms.intersection(set(entry.get("platforms") or [])):
            continue
        entries.append(entry)
    return entries


def artifact_registry_map_by_id(*, platforms: list[str] | None = None) -> dict[str, dict[str, Any]]:
    return {entry["id"]: entry for entry in artifact_registry_entries(platforms=platforms)}
